image:
  repository: olexiy/accounts-viewer
  tag: "0.1.0"
  pullPolicy: IfNotPresent

replicaCount: 1

service:
  port: 80
  type: ClusterIP

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 100m
    memory: 128Mi
