apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
  labels:
    app: {{ .Release.Name }}
  annotations:
    # DEV ONLY — replace with ExternalSecret for production
type: Opaque
data:
  DB_USER: {{ .Values.db.username | b64enc }}
  DB_PASSWORD: {{ .Values.db.password | b64enc }}
